DROP DATABASE IF EXISTS MovieCatalogue;

CREATE DATABASE MovieCatalogue;

USE MovieCatalogue;

CREATE TABLE Genre (
GenreID INT PRIMARY KEY AUTO_INCREMENT,
GenreName CHAR(30) NOT NULL
);

CREATE TABLE Director(
DirectorID INT PRIMARY KEY AUTO_INCREMENT,
FirstName CHAR(30) NOT NULL,
LastName CHAR(30) NOT NULL,
BirthDate VARCHAR(10) NULL
);

CREATE TABLE Rating(
RatingID INT PRIMARY KEY AUTO_INCREMENT,
RatingName CHAR(5) NOT NULL 
);

CREATE TABLE Actor(
ActorID INT PRIMARY KEY AUTO_INCREMENT,
FirstName CHAR(30) NOT NULL,
LastName CHAR(30) NOT NULL,
BirthDate VARCHAR(10) NULL
);

CREATE TABLE Movie(
MovieID INT PRIMARY KEY AUTO_INCREMENT,
GenreID INT NOT NULL,
DirectorID INT NULL,
RatingID INT NULL,
Title CHAR(128) NOT NULL,
ReleaseDate VARCHAR(30) NULL,
FOREIGN KEY fk_Movie_Genre(GenreID)
REFERENCES Genre(GenreID),
FOREIGN KEY fk_Movie_Director (DirectorID)
REFERENCES Director(DirectorID),
FOREIGN KEY fk_Movie_Rating(RatingID)
REFERENCES Rating(RatingID)
);

CREATE TABLE CastMembers(
CastMemberID INT PRIMARY KEY AUTO_INCREMENT,
ActorID INT NOT NULL,
MovieID INT NOT NULL,
Role CHAR(50) NOT NULL,
FOREIGN KEY CastMember_Actor(ActorID)
REFERENCES Actor(ActorID),
FOREIGN KEY CastMember_Movie(MovieID)
REFERENCES Movie(MovieID)
);





